### ISSUE TITLE
17号以后wsm无法解包出moc3文件

### ISSUE THREAD

**Issue by Tagerity** [varieget/crack-wsm-live2d#2]
貌似从17号开始创意工坊的模型预览就从前端改到了后端，前端获取的wsm里面删掉了moc3模型文件，改用websocket进行后端渲染传输到前端了。只恨没早点发现这个git，爬了所有的wsm文件，已经晚了。不知作者之前爬没爬过wsm

**Comment by varieget** [comment]
大致看了下创意工坊现行的 Live2D 加载方式，发现有以下变化。

简单而言，原本交给 [Cubism SDK for Web](https://www.live2d.com/download/cubism-sdk/download-web/) 在前端读取的 moc3 得到 `Model` 的方式，

变成了在后端通过 Cubism SDK 读取 moc3 得到 `Model` 后，再用 WebSocket 传输 `Model` 到前端。

这里存在一个问题，就是从 moc3 得到 Model 是容易的，这很轻易就可以通过 SDK 实现，

但是，通过 Model 得到 moc3 是困难的，除非 Live2D 官方开源了 SDK 里经过 [Emscripten](https://github.com/emscripten-core/emscripten) 编译的 Core 部分。

<details>
<summary>这里附上相关细节</summary>

### 原本的加载方式

1. 前端解包 wsm 文件（包含 moc3）

2. 将 moc3 喂给 ArrayBuffer

3. 通过 Cubism SDK 提供的 `Moc.fromArrayBuffer`，得到 Moc

4. 通过 `Model.fromMoc` 得到 Model

### 现行的加载方式

1. 前端解包 wsm 文件（**不包含** moc3）

2. 通过 WebSocket 加载 Model

    发送 `ping`，接收到经过 zstd 压缩后的 `Model`，通过 [zstd-codec](https://github.com/yoshihitoh/zstd-codec) 解压后，

    接着使用b站自己的 `decode` 方法，就可以得到 `Model`。

    这个 Model 就是 Cubism SDK 能够识别的 Cubism model 类型。
</details>

**Comment by varieget** [comment]
我没有爬过 wsm，但是往乐观的想，至少目前的 Model 仍然可以通过前端获取。

以及，decode 函数还没采用 wasm，至少过程还是清晰的。

**Comment by Tagerity** [comment]
那看来是获取无望了 唉 可惜了 谢谢作者的回复
