### ISSUE TITLE
"command error."

### ISSUE THREAD

**Issue by Thaumaturge2020** [varieget/crack-wsm-live2d#7]
The problem I encounter is listed as follows:
![image](https://github.com/user-attachments/assets/8a5cf6bf-ed51-4f2a-a2d4-b173d26af223)

it seems that it just simply can't run.

**Comment by varieget** [comment]
try `npm i`

**Comment by varieget** [comment]
用 npx 是不用把 repo clone 下来的，直接运行就好。

或者，安装依赖后直接运行

```
npm i
node ./bin/wsm.js e ./11454.wsm ./dist
```
